### ISSUE TITLE
What is readFile?

### ISSUE THREAD

**Issue by onmyway133** [MostlyAdequate/mostly-adequate-guide#165]
I was really excited to start [chapter 9](http://drboolean.gitbooks.io/mostly-adequate-guide/content/ch9.html#) to learn about Monad, until the section `Mixing Metaphors`

```
//  cat :: IO (IO String)
var cat = compose(map(print), readFile);

cat(".git/config")
// IO(IO("[core]\nrepositoryformatversion = 0\n"))
```

> What we've got here is an IO trapped inside another IO. To work with it, we must map(map(f)) and to observe the effect, we must unsafePerformIO().unsafePerformIO()

What is the type of `readFile` and `print`? What does it mean by saying "an IO trapped inside another IO"? What does `map(map(f))` mean?
 
I recalled from [chapter 8](http://drboolean.gitbooks.io/mostly-adequate-guide/content/ch8.html#) about the type of `readFile`, and it returns `Task`, not `IO`

```
// Node readfile example:
//=======================

var fs = require('fs');

//  readFile :: String -> Task(Error, JSON)
var readFile = function(filename) {
  return new Task(function(reject, result) {
    fs.readFile(filename, 'utf-8', function(err, data) {
      err ? reject(err) : result(data);
    });
  });
};
```

Maybe I miss something, please explain, many thanks :]

**Comment by DrBoolean** [comment]
Hi @onmyway133!

`readFile` and `print` were a bit hypothetical in this example, but here's what I was thinking:

```js
var fs = require('fs');

//  readFile :: String -> IO String
var readFile = function(filename) {
  return new IO(function() {
    return fs.readFileSync(filename, 'utf-8');
  });
};

//  print :: String -> IO String
var print = function(x) {
  return new IO(function() {
    console.log(x);
    return x;
  });
}
```

When we `map(print)` over the result of `readFile`, we get an `IO (IO String)` because `print` introduces a second `IO`. So to work with the `String` inside of the two `IO`s, we'd have to `map(map(f))` where `f` is any function that takes our `String`.

I hope that helps a bit. Definitely try it out in console by requiring code/part_2/support.js.

I'll try to add these into the book so it's not confusing for others.

**Comment by onmyway133** [comment]
@DrBoolean thanks a lot, that clarifies things :]
