### ISSUE TITLE
Theory about Monad

### ISSUE THREAD

**Issue by onmyway133** [MostlyAdequate/mostly-adequate-guide#167]
I'm reading about theory section of [Monad](http://drboolean.gitbooks.io/mostly-adequate-guide/content/ch9.html#). If I translate it to Maybe, is my understanding correct?

## associativity
```
compose(join, map(join)) == compose(join, join)
```

```
var ma = Maybe.of(5)
ma.map(join).join() == ma.join().join()
```

## identity for all (M a)
```
compose(join, of) == compose(join, map(of)) == id
```

```
ma = Maybe.of(5)
ma.of().join() = ma.map(of).join() == id
```

> If we start at the top left heading right, we can see that of does indeed drop our M a in another M container.

How does `ma.of()` work?

> Moving right to left, we see that if we sneak under the covers with map and call of of the plain a, we'll still end up with M (M a) and joining will bring us back to square one

Inside `ma` is `a`, how does `a.of` work ?

**Comment by DrBoolean** [comment]
You've got it, but we need to start with `M(M(a))` for both of these:

For associativity, since we're joining twice, it must be a `Maybe(Maybe(x))`

```js
var mma = Maybe.of(Maybe.of(5))
mma.map(join).join() == mma.join().join()
```

For `of`, it takes any value and places it `Maybe` so we're proving that nested Maybe's work okay with it.

```js
Maybe.of(Maybe.of(2)).join() // Maybe(2)
Maybe.of(2).map(Maybe.of).join() // Maybe(2)
id(Maybe.of(2)) // Maybe(2)
```

**Comment by ChetHarrison** [comment]
Brian,

regarding your implementation of “Maybe.of” what are your thoughts on this discussion?

https://github.com/fantasyland/fantasy-land/issues/85 <https://github.com/fantasyland/fantasy-land/issues/85>

Thanks

Chet

On Sep 15, 2015, at 12:42 PM, Brian Lonsdorf <notifications@github.com> wrote:

You've got it, but we need to start with M(M(a)) for both of these:

For associativity, since we're joining twice, it must be a Maybe(Maybe(x))

var mma = Maybe.of(Maybe.of(5))
mma.map(join).join() == mma.join().join()
For of, it takes any value and places it Maybe so we're proving that nested Maybe's work okay with it.

Maybe.of(Maybe.of(2)).join() // Maybe(2)
Maybe.of(2).map(Maybe.of).join() // Maybe(2)
id(Maybe.of(2)) // Maybe(2)

**Comment by DrBoolean** [comment]
I think the best implementation is having `Maybe.fromNullable` be a function that does a null check and return `Just/Nothing`. However, I find the two subtypes make it dramatically harder to understand the type (see `Either`) so I kept it simple for the book.

Several weeks ago I added a (hopefully) clarifying paragraph:

> I'd be remiss if I didn't mention that the "real" implementation will split Maybe into two types: one for something and the other for nothing. This allows us to obey parametricity in map so values like null and undefined can still be mapped over and the universal qualification of the value in a functor will be respected. You'll often see types like Some(x) / None or Just(x) / Nothing instead of a Maybe that does a null check on its value.

Right above: https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch8.md#pure-error-handling

**Comment by ChetHarrison** [comment]
ok. I’ll need to absorb all this a little more. I tried dropping your examples on the ramda-fantasy Maybe and had some issues. I have been reading through the code to understand the different implementations.

On Sep 15, 2015, at 1:00 PM, Brian Lonsdorf <notifications@github.com> wrote:

I think the best implementation is having Maybe.fromNullable be a function that does a null check and return Just/Nothing. However, I find the two subtypes make it dramatically harder to understand the type (see Either) so I kept it simple for the book.

Several weeks ago I added a (hopefully) clarifying paragraph:

I'd be remiss if I didn't mention that the "real" implementation will split Maybe into two types: one for something and the other for nothing. This allows us to obey parametricity in map so values like null and undefined can still be mapped over and the universal qualification of the value in a functor will be respected. You'll often see types like Some(x) / None or Just(x) / Nothing instead of a Maybe that does a null check on its value.

Right above: https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch8.md#pure-error-handling <https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch8.md#pure-error-handling>

**Comment by DrBoolean** [comment]
Definitely let me know if you are hitting issues. The implementation might be different, but the semantics of `map`/`ap`/`chain` should all (by law) be the same. I may have overlooked something in an example or my "simplified" Maybe could have unforeseen issues.

**Comment by ChetHarrison** [comment]
sure. Sorry for the email posts (kinda messy) I'll post here.

**Comment by onmyway133** [comment]
@DrBoolean thanks. All are clear. But this confuses me

```
compose(join, of) == compose(join, map(of)) == id

Maybe.of(Maybe.of(2)).join() // Maybe(2)
Maybe.of(2).map(Maybe.of).join() // Maybe(2)
id(Maybe.of(2)) // Maybe(2)
```

How can `compose(join, of)` be exampled by `Maybe.of(Maybe.of(2)).join()`?

**Comment by DrBoolean** [comment]
Glad to help!

I should have written it like this:

```js
compose(join, of) == compose(join, map(of)) == id

var m = Maybe.of(100);
var of = Maybe.of;

compose(join, of)(m)
// Maybe(100)

compose(join, map(of))(m)
// Maybe(100)

id(m)
// Maybe(100)
```

They are dealing with "inner" or "outer" associativity of joining

**Comment by xujihui1985** [comment]
I image monad as a bubble in real life, when 2 bubble met, they merge into 1 bubble.

Maybe.of(100) is like put 100 into a bubble(container), then map over it is like to put the bubble in to another bubble, then join them into one bubble.
