### ISSUE TITLE
Bind/Chain

### ISSUE THREAD

**Issue by onmyway133** [MostlyAdequate/mostly-adequate-guide#169]
Hi, In [chapter 9, section My chain hits my chest](http://drboolean.gitbooks.io/mostly-adequate-guide/content/ch9.html)

> You might have noticed a pattern. We often end up calling join right after a map. Let's abstract this into a function called chain.

```
//  chain :: Monad m => (a -> m b) -> m a -> m b
var chain = curry(function(f, m){
  return m.map(f).join(); // or compose(join, map(f))(m)
});
```

This makes good encapsulation because we hide the `__value` inside monad, but I often see `bind` explained like this
```
var bind = curry(function(f, m){
  return f(m.__value);
});
```

What should be the preferred way?

**Comment by DrBoolean** [comment]
While that `bind` is valid, it doesn't get the "effect" for free. The idea is that if we have a `map` which has some effect or traverses the data type, we would want to use it rather than repeat ourselves in `bind/chain`. Bind, Chain, and FlatMap are all different names for the same thing. FlatMap is, by far, my favorite name and hints towards the right path :)
