### ISSUE TITLE
Alternative implementation for chapter 8

### ISSUE THREAD

**Issue by geohuz** [MostlyAdequate/mostly-adequate-guide#217]
I was thinking of an other way of implementing the zoltar function, for the sake of my lack of knowledge of js object constructor :-), 

```javascript

  var moment = require('moment');
  var R = require('ramda');

  var fortune = R.compose(R.concat("If you servive, you will be: "), R.add(1));

  var getAge = R.curry(function(now, user){
      var birthdate = moment(user.birthdate, 'YYYY-MM-DD');
      return !birthdate.isValid() ? {"error":"Birth date could not be parsed"} : now.diff(birthdate,'years');
  });

  var zoltar = R.compose(console.log, R.either(R.prop('error'), fortune),
                        getAge(moment())
  );
```

Can anybody point out the pros and cons of usage in this way?

Thanks...

**Comment by KtorZ** [comment]
Have a look at [ramda documentation](http://ramdajs.com/docs/#either), the either function you're using here has nothing to do with the functor introduced in the chapter.

Talking about Either functor, you may see it as a structure that can hold either a value or another (materialized with the Left and Right constructor). 
Then, and this is maybe a bit confusing, Brian defines an `either` function used to apply a function or another depending of the nature of the value hold by the Either functor.
Still, the idea is that the `getAge()` function returns a functor on which you can map and ap. In your implementation nonetheless, your `getAge()` function return either an error object or an integer. 

If you try to write the type signature of your `getAge()` function, you're going to face some trouble as it has currently several return types (that's why either stands for, a single return type, but which behave differently depending on its intrinsic value.

Also, I may be wrong but, I don't think that the point of those examples was about the `constructor` *pattern* in js. You should thereby focus more on the possibilities offered by using functional structures such as Either or Maybe, more than focusing on the implementation of contingent function.    

Hope it helps :)

**Comment by geohuz** [comment]
I understand it, thanks a lot!
