### ISSUE TITLE
IO questions

### ISSUE THREAD

**Issue by laduke** [MostlyAdequate/mostly-adequate-guide#276]
Can you folks suggest an implementation of IO? If it's just the one from this repo's support.js, that's fine. But I'm curious why libraries that have everything else don't include it. I searched through a bunch mentioned in the book like rambda, folktale... 

Being a slow person, I think I should wrap onclicks in an IO? I'd love an example in some chapter that has some global state and some mouse click handlers. Like just increment a number with a button press.

**Comment by safareli** [comment]
monet.js has io monad.
also you could use folktail's data.task instead of io.

**Comment by xujihui1985** [comment]
IO is just the monad that warp the action that will have side affect, like you can wrapper the `fs.readFile` in a IO monad, the `run` it to execute the side affect or lift it to a new IO monad. The idea of functional programming is to keep the side affect as limit as possible

**Comment by DrBoolean** [comment]
Hi @laduke!

If you have a lazy data structure like Task or EventStream (some are not lazy so beware), you don't need IO at all. It's useful for synchronous stuff which is not very common in JS. Even then I tend to stick with Task() and just wrap things like:

```
const readFile = x =>
  new Task((rej, res) =>
    res(fs.readFileSync(x)))
```

You were totally correct to wrap clicks in `IO`, but I prefer the FRP approach that uses lazy EventStreams

So `IO` is really useful in swift/purescript/haskell/scala which is why i put it in the guide, but we don't really need it in JS.

**Comment by laduke** [comment]
thanks, everyone!
