### ISSUE TITLE
unsure what the advantage of exposing the constructor is.

### ISSUE THREAD

**Issue by sourcevault** [MostlyAdequate/mostly-adequate-guide#298]
In the book @DrBoolean exposes the constructor method `.of` - what are the pros and cons of doing something like this :

``` livescript

main = (value) ->

    @value = value


main.of = (x) -> new main x

main.prototype.bar = -> 'bar function'


main.prototype.foo = -> 'foo function'

module.exports = main.of # expose only of method

```

OR

``` livescript

main = (value) ->

    @value = value


main.of = (x) -> new main x

main.prototype.bar = -> 'bar function'


main.prototype.foo = -> 'foo function'

module.exports = main # expose entire api

```

**Comment by KtorZ** [comment]
JavaScript contexts can be tricky. Even in CoffeeScript, you might encounter some issues by just exporting the reference to the function. Should you want to export only the method itself, make sure to bind the context with it. 

In this specific case.. The function `of` doesn't make use of the context (`this`) so, it is fine to just pass the function. It's a matter of taste, but exporting the object rather than the function is safer in case you later on decide that we want to access some `this` in your `of` function.

**Comment by partially-applied** [comment]
hey @KtorZ  I really appreciate your help ! 

So you are saying that in situations where I would access the `this` method in `of` I need to export the object ?

**Comment by JAForbes** [comment]
A few reasons I can think of, there may be more

1. `of` is easier to compose point free than new
2. `of` allows each implementation to decide the underlying creation mechanism, whereas `new` doesn't
3. `of` acts as a run time type hint for functions like `R.sequence` or `R.traverse`

**Comment by partially-applied** [comment]
@JAForbes  

The point free argument - you can do point free with functions like that too ! 

```livescript

lib = import 'lib'

(lib!).foo(f).bar(g)

```

**Comment by partially-applied** [comment]
@KtorZ 


```livescript

main = (config) !-> 
 
	lo.defaults-deep config,defaults-config

	@log = simple-log config.simple-log

	{fns} = config

	for I in Object.keys fns

		@[I] = fns[I]


# under what circumstances will you need to use this variable in of method ?

main.of = (config = {}) -> new main config

```

you do most of your binding in the `main` functions instead of `main.of`

So my question is I am still trying to figure out why you would need to expose the main.of constructor to the user ? 

What is the difference between:

```livescript

main(config).map(f)

```


```livescript

main.of(config).map(f)

```

I think I am missing something big. 

The only thing I can think of is you have *mutiple* types of constructors that do different things, but in that case you can just pass a config variable ?

**Comment by JAForbes** [comment]
@partially-applied sorry I misunderstood your question.  I thought you were asking why use `of` instead of a constructor function.

You mean specifically with modules why only expose `of` instead of the entire object?

I can't speak for the author, but I assume it is just to expose the minimum api surface required.  Probably in the book only the `of` function is used, so exposing anything more than that just adds complexity for the consumer of the module.

Most Fantasy Land implementations expose the entire object though, because there is a need to access static methods on the object.

**Comment by partially-applied** [comment]
Oh right. I think I get it @JAForbes 

So lets say we have a module


```livescript

M = require 'test-module'

{compose} = require 'ramda'

ins = M.of()

ins.map(f).ap(g)

o1 = M.ap(g,M.map(f,ins)) 


pipeline = compose (M.map g),(M.ap f)


o2 = pipeline ins

o1 == o2 # true

```

So if you want to expose API that can do these tricks you expose the entire module

I am thinking about this of the top of my head from looking at `most.js`, but am not sure if this is the only benefits.

**Comment by JAForbes** [comment]
I think it is a general principle some programmers (including me) abide
by.  Expose the minimum possible interface necessary, nothing more, nothing
less.  It puts less pressure on documentation, it makes it easier to update
libraries without making breaking changes.  Its also a lot simpler for the
consumer of the library to get up and running.

For something like a stream library, you could have a lot of static
operators, so it makes sense to expose a larger interface.  It is always
easier to add to an interface than to remove from it, so it is important
that we only expose things when we know they are needed.

Other programmers follow other philosophies and that is fine too.  It
really depends on the context of the application and who the target
audience is.  But I think that is the answer to your original question.
The book is probably just exposing the minimum required interface.
