### ISSUE TITLE
Chapter 3 pure function is impure

### ISSUE THREAD

**Issue by awaltert** [MostlyAdequate/mostly-adequate-guide#319]
In chapter 3, there is given an example under the point `reasonable`. 
The description make the assertion that the functions `decrementHP`,
`isSameTeam`and `punch`are all pure.

In my point of view, this is not correct for the `punch`function. In fact, this function
consumes `isSameTeam` and `decrementHP` over its context (scope). Therefor, this function
has this hidden dependencies and can not be asserted as pure:  

```javascript
var punch = function(player, target) {
  return isSameTeam(player, target) ? target : decrementHP(target);
};
```
To become pure, both functions should be declared as function arguments for `punch`.

```javascript
var punch = function(isSameTeam, decrementHP, player, target) {
  return isSameTeam(player, target) ? target : decrementHP(target);
};
```

What do you think?
If you agree, i'd be happy to can make the PR 😄 

Best,
André

**Comment by christiantakle** [comment]
Well yes and no.  Its pure in the sense of referential transparency.

However since this is javascript one could
```js
punch(a,b) == punch(a,b) // True
isSameteam = undefined; // This would not compile in other functional languages 
punch(a,b)                         // Error!
```

**Comment by fix-fix** [comment]
`punch` is pure on its own, because it's not using free variables (and you don't have to provide `isSameTeam` and `decrementHP`, because they are already bound to the common scope, the binding just has no noticeable special syntax).

The only problem is that in previous versions of javascript (ES5 or older) you could easily override bindings of the current scope and there was no protection from that, other than hiding the function's scope (e.g. by wrapping it in another function).

**Comment by awaltert** [comment]
In my opinion, the function is not pure, because the result depends on the values present in `isSameTeam` and `decrementHP`during the evaluation. Thanks @christiantakle for providing an example which shows the situation. 

In fact, the function depends on its context. You can't test the function in isolation without providing a matching context. In this seems to be a violation against the definition that a pure function only depends on its arguments.

What is the difference to the example provided at the beginning of the chapter 3?

```javascript
// impure
var minimum = 21;

var checkAge = function(age) {
  return age >= minimum;
};

```
Here you can find the same situation, the `checkAge` function has this hidden dependency against the scope property `minimum` and it is assest as impure.

**Comment by christiantakle** [comment]
Well thats the caveat in newer versions of Javascript one could write

```js
const minimum = 21;

const checkAge = function(age) {
  return age >= minimum;
};

minimum = 'blah' // Error
```

Thus solving the problem N.B. even with `const` there are cases where unwanted mutation can happen.

You have to consider scope as well consider this:
```js
// MyModule.js
var minimum = 21;

var checkAge = function(age) {
  return age >= minimum;
};

module.exports = { checkAge: checkAge }
```
Now `checkAge` is the only function that have `minimum` in scope making it 'safe'. A module is effectively a closure e.g.
```js
(function(minimum) {
  'use strict';

  var checkAge = function(age) {
    return age >= minimum;
  };

  return checkAge;
}(18));
```

Which is why my response was *yes and no* in other languages this wouldn't be a problem but it can be in Javascript which is a flaw in the language not the concept.

**Comment by alex-dellagi** [comment]
Yes, but nevertheless the currently existing example in the book is not consistent :)

**Comment by awaltert** [comment]
@christiantakle I'm aware of the fact, that newer language constructs introduce a constant binding. In the provided examples within the book, these language features are not utilised and the external state (`minimum`, `isSameTeam`, `decrementHP`) is mutable.

For the reader is it misleading to call one example impure and another pure, where as both uses the same mutable constructs.  
Thus, i complain about the provided examples and not the language constructs.

**Comment by christiantakle** [comment]
@alex-dellagi @awaltert 

I'm confused I'm not saying you're wrong. I think the point is more show/explaining the general concept and not the quirks of a specific language.

I propose that a better solution would be changing wording rather than code to promote the concept more than the specific language details.

Since the examples are all ready more accurate in #273

**Comment by BLamy** [comment]
Would injecting the functions first be more preferred?

'''Js 
var punch = (isSameTeam, decrementHP) => (player, target) => {
  return isSameTeam(player, target) ? target : decrementHP(target);
};
'''

**Comment by yang-wei** [comment]
a pure function is defined as 
 - always return same value when same argument is passed in
 - does not produce side effects

which the function:
```js
var punch = function(player, target) {
  return isSameTeam(player, target) ? target : decrementHP(target);
};
```
fullfilled. So this function is pure as long as `isSameTeam` and `decrementHP` are pure.


As @christiantakle said,

> If one aims for Pure in Javascript it might loose to much practicality.

is very true.

**Comment by awaltert** [comment]
@yang-wei As already discussed before, the problem is that you can't really rely on the bindings of `isSameTeam`and `decrementHP`. Nevertheless the functions themselves are pure, their bindings are also mutable. As mentioned, in #273, the bindings are constant and therefore much more reliable. 

@christiantakle I would agree with your proposal to extend the description for making it clearer to the audience.  
What I want to address is the fact, that in the very beginning of the chapter, there is an example where you can find a function which relies on a mutable scope value `minimum`. This is described as impure, whereas the `punch` function uses exactly the same principle and is assessed as pure. In my point of view, this is misleading and inconsistent, especially for unexperienced readers. 

This is what I complain and also @alex-dellagi seams to do. :smile:

**Comment by bloadvenro** [comment]
@awaltert 
> this is misleading and inconsistent, especially for unexperienced readers.

Sorry. I just can not imagine totally inexperienced javascript developer reading this book :smile: 

> In my opinion, the function is not pure, because the result depends on the values present in isSameTeam and decrementHPduring the evaluation.

The example with `punch` is totally ok for me. Both functions are pure so `punch` is also pure, isn't it?

> In fact, the function depends on its context. You can't test the function in isolation without providing a matching context.

If my function uses `path.join` or `md5("I'm pure!")` (or any language built-in pure function) inside won't it be pure by itself??

> As already discussed before, the problem is that you can't really rely on the bindings of isSameTeamand decrementHP.

In javascript you can not be sure of many things. You can easily replace `Array.prototype.map` or perform `Math.pow = 1`. We use linter/flow/typescript to make javascript better. Reassignments for function declarations are restricted in such tools.

> What I want to address is the fact, that in the very beginning of the chapter, there is an example where you can find a function which relies on a mutable scope value minimum. This is described as impure, whereas the punch function uses exactly the same principle and is assessed as pure.

If we explain everything too much in detail, examples will be over-complicated. In the case of `minimum` we're dealing with __implicit parameter input__ which has to be explicit.

**Comment by babakness** [comment]
Hmm.. I've been practicing some Lambda Calculus (just a small amount). I went through and re-derived the Y-Combinator and all that on my own. I could be wrong in what I'm saying but I'll just go ahead and say it.

First, consider the following definitions for True and False

```javascript
const Identity = a => a
const Kestral  = a => b => a
```
From this we can derive Kite
```javascript
const Kite = Kestral(Identity)
// Kite = a => b => b
```

Kite is a pure function. And a combinator, because it does not reference any free variables and can be expressed purely from other combinators. You can reduce down until all the other combinators disappear. What you can't take for granted however is this

```javascript
sum = (num,total) => num === 0 ? total : sum(num - 1, total+num)
```

Because sum is given in terms of itself. This is where Y-Combinator comes in.

**Comment by Serentty** [comment]
In my opinion, the function is pure, provided that impure code that mutates its obstensibly constant dependencies is not added elsewhere in the code. In a language that enforces purity, this would not be an issue, but in JavaScript, it's possible for a bad apple to spoil the bunch when it comes to purity. I would argue that passing functions that are de facto constant around as explicit dependencies just to maintain theoretical purity, without regard for whether or not a function is pure in practice, is overkill. After all, this book is supposed to teach readers to write actual, practical functional code. In a purely functional language, this workaround would not be needed, since purity is guaranteed. In an impure one, it serves only to maintain theoretical purity, when practical purity is already achieved. Indeed, the threat of cosmic rays flipping bits in memory is a threat to the purity of any code, yet it is so far outside of the realm of practicality that it is ignored. While the threat presented here is much more realistic, and likely to occur at least occasionally by accident, such issues are inevitable in an impure language, and trying to account for them merely distracts from the underlying ideas by focusing on the idiosyncrasies of JavaScript, as opposed to the mathematical concepts underneath, which are transferable between languages.

**Comment by kuzarth** [comment]
So, where's the line when the function stops being pure?
The chapter has the following statements:
> Any interaction with the world outside of a function is a side effect.
---
> Side effects disqualify a function from being pure. And it makes sense: pure functions, by definition, must always return the same output given the same input, which is not possible to guarantee when dealing with matters outside our local function.

```js
const punch = (a, t) => (isSameTeam(a, t) ? t : decrementHP(t));
```

Does the `punch` function *deal with matters outside*? Does it matter, that outside functions are pure? Can we use pure functions inside other pure function just referring to them in functional programming? Is it ok? It's a side effect, that disqualifies a function from being pure, isn't it?

I'm confused here.

**Comment by KtorZ** [comment]
Thanks @Serentty.
I'll no close this issue for it is not relevant anymore; in summary however:

- A function is pure if its output is solely determined by its inputs (that's what "without side effects" means).
- A pure function calling other pure functions is still pure, regardless if they're passed as arguments or not (note that we disregard the case in JavaScript where function definitions could be changed at runtime... seriously, do yourself a favor and don't do that please!)
- All-in-all, one could replace any call to a pure function by the actual content body of that function. This is called referential transparency and is something you get for free with pure functions.

A few examples of impure functions or side-effects:

- Getting the current time 
- Unseeded random generator
- Reading / Writing a file from / to disk
- Reading / Writing from / to a database
- Sending an HTTP request
- Incrementing a global counter
- Writing a line on the console

**Comment by zhuanyongxigua** [comment]
I'm also confused with the following statements in this chapter:
> Any interaction with the world outside of a function is a side effect.

What the meaning of the word "interaction"?Call a pure function in a pure function is not a kind of "interaction"?

**Comment by KtorZ** [comment]
> Is use a immutable shared state "minimum" a kind of "interaction"?

No :). I'll genuinely point you to my previous comment -> https://github.com/MostlyAdequate/mostly-adequate-guide/issues/319#issuecomment-385911626

The question you should ask yourself when thinking about purity is basically "Do I have the guarantee that a given action will always yield the same result?". If so, you should be able to substitute every calls by their definition and get what result would be obtained by applying a given input to a function. If you can do that, your function is most likely pure. 
Introducing things like randomness, current time or I/O introduces uncertainty in the system. These are rather unpredictable sources of events.
