### ISSUE TITLE
hi,is anybody talk with me?

### ISSUE THREAD

**Issue by laureler** [MostlyAdequate/mostly-adequate-guide#344]
im a software engineer from china. as you konw,china own the GFW,and i d like to talk with someone with english. no matter where are you from(first language with english is better). just make a friend to talk. and i can help you to study chinese in night(i was free in 20:00 - 22:00).please leave you message. im alone in china,i can not travel the world,just talk to me or may be let me know im not alone.
im sorry for this message,it should be write some question or suggestions,but i can not find a way to know some foreigners. please do not delete this.

**Comment by KtorZ** [comment]
Hey!
Firstly, be sure you're not alone on the Internet. However, I do believe that a code repository isn't the best place for you to find a discussion partner, except if it's something related to code of course. 

Have you try to look up some existing chat app or online communities (might they even be anonymous). I am not sure about what is blocked by the Chinese firewall but provided you can already have access to github, you have probably access to a wide part of the Internet (through a VPN I guess). Maybe could you give a try to 9gag? The community is quite International and I do believe they have different chat rooms connecting people around various topics. 

I wish you the best and will however close the issue since it isn't relevant to this repository (you may still add comment to it though).

**Comment by Jogai** [comment]
Slack or [Gitter](https://gitter.im/home/) is more intended for 'talk'. I reccomend reddit over 9gag as a starting place for various communities.
