### ISSUE TITLE
How does exercise 1 support.js work without exporting?

### ISSUE THREAD

**Issue by Hemaolle** [MostlyAdequate/mostly-adequate-guide#350]
I'm pretty new to the Javascript world so I'm probably missing something here. I'm having a difficult time trying to understand the idea of the https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part1_exercises/support.js file in exercise 1 code. To me it seems that nothing is exported in that file and I don't understand how the functions could then be accessed in the exercise file where it is required: https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part1_exercises/exercises/curry/curry_exercises.js#L1. Looks like the answer too is just using Ramda: https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part1_exercises/answers/curry/curry_exercises.js.

Perhaps the point of the `support.js` is just to provide some examples for implementations of functional programming concepts?

**Comment by KtorZ** [comment]
You're right. Importing the `support.js` file does nothing in Node.js since nothing is exported nor placed in the global scope. 
The exercises have actually been through quite a lot of changes and rework and the `support.js` is now mostly use a reference from within the book. I have started some work to review this whole exercise sections (and include them in the book directly to make it more interactive) as we keep having issues raised on this topic which in the end appears to be rather unclear.

**Comment by Hemaolle** [comment]
Ok, thanks for the clarification :slightly_smiling_face:

**Comment by Hemaolle** [comment]
Oops, actually the `support.js` seems to indeed define functions in the global scope starting from line 54 (https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/code/part1_exercises/support.js#L54) which are indeed accessible when the file is imported and also used in the exercises. It looks like defining variables in modules without the `var` keyword places them in the global scope making them accessible .

**Comment by KtorZ** [comment]
which is definitely not a good practice and will be removed, hopefully, rather soon ^.^
