### ISSUE TITLE
Question about chapter 9.

### ISSUE THREAD

**Issue by WinterCore** [MostlyAdequate/mostly-adequate-guide#436]
Hi.
I'm pretty sure I'm missing something here.
```js
// readFile :: Filename -> Either String (Task Error String)
// httpPost :: String -> Task Error JSON
// upload :: String -> Either String (Task Error JSON)
const upload = compose(map(chain(httpPost('/uploads'))), readFile);
```
Shouldn't it just be like this ?
```js
const upload = compose(chain(httpPost('/uploads')), readFile);
```
```map``` gives the ```chain``` an unwrapped value, and ```chain``` is unwrapping it again ?
Are we assuming that the ```chain``` doesn't unwrap if it receives a normal value (nonfunctor/nonmonad) and it just gives it directly to the ```httpPost``` function (in this case). Like Promises for example ?
Thanks in advance.

**Comment by KtorZ** [comment]
Hey! 
You may want to reason about signatures here.  If we get a closer look to our friends:

```hs
map   :: Functor f => (a -> b)   -> f a -> f b
chain :: Monad m   => (a -> m b) -> m a -> m b
```

You can see a subtle difference with `chain` which actually expects a function that will return a value wrapped in a Monad. It wouldn't be very useful to have the following signature:

```hs
chain? :: Monad m => (a -> b) -> m a -> m b
```

Because since a `Monad` is already a `Functor`, `map` already gives us this ability. What `chain` does is therefore a bit more _powerful_, it allows us to apply functions inside a structure, and flatten the result at the same time. 

Now, to make this a bit more concrete, let's follow what's going on with the upload function. We have two algebraic structures that come into play:

- A Monad `Task Error`
- A Functor `Either String`

Ideally, what we are trying to achieve is: 

- Reading from a file
- And then, posting the result to an hypothetical server when it makes sense.

Let's start with `readFile`

```hs
readFile :: Filename -> Either String (Task Error String)
```

We get back an `Either String (Task Error String)`. If we want to transform the `Right` side, we have to map over it with an appropriate function. If we apply our types to the signature above for map, we get the following:

```hs
map :: Functor f => (a -> b) -> f a ->  f b
map :: (Task Error String -> Task Error JSON) -> (Either String (Task Error String)) ->  (Either String (Task Error JSON)
```

We already have the `f a ~ Either String (Task Error String)`, that's the output of the `readFile` function. So we need to provide the first part. 

```hs
fn :: Task Error String -> Task Error JSON
```

Now, when you see this, you _should_ see a Functor `Task Error` and have a immediate reflex. "How can I transform the value inside a Functor? `map`!"

So, if we _apply_ `map` again to our types:

```
map :: Functor f => (a -> b) -> f a ->  f b
map :: (String -> JSON) -> Task Error String -> Task Error JSON
```

So we need a function from `String -> JSON`. That's embarrassing because our `httpPost` isn't really working here. 

```hs
httpPost :: String -> Task Error JSON
```

If we were to  `map(map(httpPost))`, we will end up with a 

```
Either String (Task Error (Task Error JSON))
```

That's where we're going to need `chain`. It makes sense also conceptually here. You can think of a `map` as an _immediate transformation_ whereas, `chain` convey this idea of sequentiality where the second action needs the result of the first one (we need to read the file first and then, we will be able to post the result). There are two actions that have to be chained and that's what the Monad is for.

So if we _apply_ our types to `chain`'s signature (instead of `map`):

```
chain :: Monad m   => (a -> m b) -> m a -> m b
chain :: (String -> Task Error JSON) -> Task Error String -> Task Error JSON
```
Now our `httpPost` fits perfectly for that first function. Hence our `map(chain(httpPost)`. First we map to transform the `Right` side of the `Either String` by chaining the `Task Error` inside it with another `Task Error`. Because `Either String` is at least a `Functor` and `Task Error` at least a Monad, it holds :)

**Comment by WinterCore** [comment]
Hi.
I just realized, now, that my question had nothing to do with what was actually going on. 😀
I now have a clear understanding of the benefits of the type system.

Thanks for taking your time to write a great explanation. I really appreciate your help.
