### ISSUE TITLE
Ch13 referenced in Ch12 Summary but not on master

### ISSUE THREAD

**Issue by flpStrri** [MostlyAdequate/mostly-adequate-guide#437]
The Chapter 13 is referenced – with a hyperlink – in Chapter 12 Summary section but since Ch13 is not into the master branch yet it explodes 💥 in a 404.

**Comment by flpStrri** [comment]
Yea, it is into the `ch13.md` branch, not on master.

**Comment by KtorZ** [comment]
@flpStrri Yes, it has always been like this actually ^.^
I mean, each chapter has always referred to the next one, even if the next one wasn't (isn't) yet available. This way, when a new chapter is released, one doesn't forget to update the link in the previous one!

Might be inconvenient indeed, but not so much right :no_mouth: ? Otherwise, I am happy to take a PR if it bothers you too much :blush:
