### ISSUE TITLE
Why this function is pure?

### ISSUE THREAD

**Issue by kamilwojdylo** [MostlyAdequate/mostly-adequate-guide#452]
Hello, I have started to read `ostly-adequate-guide` and in chapter 3 there is demponstration of pure function:

```
// pure
const signUp = (Db, Email, attrs) => () => {
  const user = saveUser(Db, attrs);
  welcomeUser(Email, user);
};
```

My question is: Why is this function pure if it uses functions `saveUser` and `welcomeUser` that are not passed to it as arguments?

**Comment by paroxyzm** [comment]
In my opinion, this is pure, because we are returning a function and not executing it.  The function returned is always the same. Only the inner function is not pure.   const signUp = (Db, Email, attrs) =&gt; () =&gt; {    // stuff   }  signUp is a function returning function. We can also rewrite it like this:  const signUp = (Db, Email, attrs) =&gt; functonA  const functionA = function () {      // do stuff with (Db, Email, attrs)  }  }  
                
              
               
                 
                  Dnia 15 czerwca 2018 10:14 kamilwojdylo &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Hello I have started to read  ostly-adequate-guide  and in chapter 3 there is demponstration of pure function: 
 // pure  
const signUp = (Db, Email, attrs) =&gt; () =&gt; {  
const user = saveUser(Db, attrs);  
welcomeUser(Email, user);  
}; 
 My question is: Why is this function pure if it uses functions  saveUser  and  welcomeUser  that are not passed to it as arguments?

**Comment by kamilwojdylo** [comment]
How about this function:
```
const signUp = (Db, Email, attrs) => {
  const user = saveUser(Db, attrs);
  welcomeUser(Email, user);
};
```

Is it pure?

**Comment by KtorZ** [comment]
> Is it pure?

No. Doesn't seem so. 
Ask yourself one thing: "If I execute this function, no matter the context, no matter how long the system has been running, will it return the same result for same inputs?"

Now, calling `signUp` will trigger a call to the DB:

- What if the connection to the db is broken?
- What if the db is busy and doesn't respond?
- What if the user already exists and can't be saved?

To answer those questions, you need to know the "state of the world". You can't answer them by simply looking at the inputs and looking at the function. So, the resolution of the function doesn't solely depends on its inputs and its body; it also depends on some external elements. 

Pure doesn't mean that stuff needs to be passed as arguments. You could define:

```js
const email = "always.same@email.com";
const appendAndUpper = suffix => email.concat(suffix).toUpperCase();
```

Here, `appendAndUpper` is pure. Regardless of the world, if you give an input, you will always get the same result. So, calling pure function from within a function doesn't make it impure. Dependency injection has nothing to do with purity, it's simply a mechanism to decouple portions of code.

**Comment by kamilwojdylo** [comment]
@KtorZ Thanks for explanation.
