### ISSUE TITLE
A different `chain` for `Maybe`

### ISSUE THREAD

**Issue by babakness** [MostlyAdequate/mostly-adequate-guide#453]
I was thinking in today how `Array.prototype.flatMap` is guaranteed to return an `Array`. I also noticed that there is no `chain` for `List` as implemented here. There is however an implementation here 

https://github.com/DrBoolean/immutable-ext/blob/b73f0921575ef653851ae6fbd3471a5a29befc9c/index.js#L8-L12

Which leverages the fact that a `List` type is a monoid. This Monad is also guaranteed to return a `List` 

So I was thinking a while in the shower  🛀, shouldn't a `Maybe` type also guarantee that it's `chain`/`flatMap` operation returns a `Maybe` as well?

Given the `Maybe` implementation in this book, perhaps something like this:

```javascript
Maybe.prototype.chain = function( fn ) {
  const result = this.map( fn ).join()
  return ( result instanceof Maybe ) ? result : Maybe.of( result )
}
```

Or perhaps

```javascript
Maybe.prototype.flatten = function( ) {
  return ( this.$value instanceof Maybe ) ? this.$value : Maybe.of( this.$value )
}
Maybe.prototype.chain = function( fn )
  return this.map( fn ).flatten()
}
```

**Comment by KtorZ** [comment]
Well, your question is legit in our non-typed context indeed. In a context such as Haskell or PureScript, this would be irrelevant because `chain` acts upon **the same monad** _m_. 
If you look at the signature and remember the bits we said about variables in such signatures:

```hs
chain :: Monad m => (a -> m b) -> m a -> m b
```

`m` must be the same in the whole signature every time it appears. Our implementation is a bit ... flakky indeed for one could chain Task, Identity and Maybe without JavaScript saying a damn about it :). 
And to be honest, I am still thinking about adding such check to all methods (not only `chain` actually) for all algebraic structure we defined. In a way, it clutters the code a bit, but also makes the idea much clearer.

**Comment by babakness** [comment]
Hi, so if I understand correctly and express that type signature in TypeScript in some `chain` method and a `flatMap` method like the one shown in my post above.

```typescript
export class Just<A> {

  static of<T>(value: T) {
    return new Just(value);
  }
  constructor(readonly value: A) {}

  flatten(): Maybe<A> {
    return this.flatMap( identity )
  }

  chain<B>( fn: (a: A) => Maybe<B>): Maybe<B> {
    return fn(this.value)
  }

  flatMap<B>( fn: (a: A) => B | Maybe<B>): Maybe<B> {
    const isMaybe = ( value ): value is Maybe<B> => {
      return ( value instanceof Just || value instanceof Nothing || value === nothing)
    }
    const result = fn( this.value )
    return isMaybe( result ) ? result : Maybe.of( result )
  }

}
```

I believe the `chain` method here roughly matches the Haskell version. Some function `chain` take a `fn` that lifts `a` into a Maybe of `b`, applied to some Maybe of `a` to yield some Maybe of `b`

The `flatMap` here seem kind of correct as well but behaves differently. I'm not sure if Haskell lets you overload types, probably not, (warning: I don't currently know Haskell)

```haskell
flatMap :: Monad m => (a -> b) -> m a -> m b
flatMap :: Monad m => (a -> m b) -> m a -> m b
```

Perhaps this is the right way http://babel.ls.fi.upm.es/~pablo/Papers/Notes/typeClassOvld.html

Anyway, this `flatMap` behaves more like `then` from Promises in that it will wrap a value back into a Promise if not already a Promise. Yet this isn't that different than a `map` followed by a `flat`. First `map` lifts the function over some thing in the functor, resulting in a functor with the value, then we flatten that value down one level... kind of like `Array.prototype.flatMap`

All told, I'm not really sure which is the right implementation. If I decided to keep `flatMap`, what should I call it? If I kept `flatMap` what should I call `chain`?

Thanks for sharing some knowledge / understanding.

**Comment by KtorZ** [comment]
> All told, I'm not really sure which is the right implementation. If I decided to keep flatMap, what should I call it? If I kept flatMap what should I call chain?

Hmmmm... Your "first version" of `flatMap` is actually what we call `fmap` in the book (and in Haskell, F#, fantasy-land etc.) though your constraint is a bit too strong. There's no need for `m` to be a Monad for such operation, having a Functor for such operation is sufficient. So in theory you have:

```
fmap :: Functor f => (a -> b) -> f a -> f b
chain :: Monad f => (a -> m b) -> m a ->  m b
```

I'd rather expose `fmap` and `chain` than `flatMap` or `then` because their meaning is clear and well-established. In my opinion, the current behavior of `then` in JavaScript's promises is an abomination and doesn't help developers understanding what's going on (you return either a Promise or a value, and it gets "wrapped" in a Promise anyway if it's not? .... Meh.) 

Haskell lets you "overload types" through type-classes which is a bit similar to interfaces in OO. Also a preferred approach imo if you want to have functions working with multiple types that have, a priori, no reason to be associated with each others.

**Comment by babakness** [comment]
@KtorZ Yeah I'm not convinced that `then` is so terrible. Conceptually if behaves like this:

1. map
2. flat

Not so different than this behavior really:

```javascript
[1,2,3].flatMap( i => i * 2); // [2,4,6]
[1,2,3].flatMap( i => [ i * 2 ] ); // [2,4,6]
```
If you map to a value inside a Promise, you get that value in a Promise. Then that value is flattened, resulting in a value in a Promise.

Next, if you map to a Promise inside a Promise, the you first get a Promise inside a Promise. Then that value flattened down one level, resulting in a value in a Promise.

It isn't so wishy washy really. It is literally a `map` then a `flatten`. It doesn't require a logical condition, it is the result of a composition of two operations.

Also, I realize my naive type for `flatMap` is condition based. So I reworked it after some study and broke `Typescript` (or at least broke my understanding of the limits of Typescript) in the processes. Here is a link to that issue and the example code, if you are interested. It is called `makeTrouble` in this example:

https://github.com/Microsoft/TypeScript/issues/25143

Also the signature of this `flatMap`, to `map` then `flatten`, will have the same signature as `fmap` but it isn't the same thing.

**Comment by babakness** [comment]
OK I think I found the offending behavior. These first two cases don't seem bad:

```javascript
Promise.resolve(2).then( i => i * 2 ).then( console.log ) // 4
Promise.resolve(2).then( i => Promise.resolve( i * 2 )).then( console.log)
```

This third case however seems different
```javascript
Promise.resolve(2).then( i => Promise.resolve( Promise.resolve(i * 2) )).then( console.log)
```

It looks like what is going on here is a complete flattening of all nested layers. Something like

1. map
2. flattenAll

I can see that this isn't standard. Not sure if it is mathematically invalid but I do understand the upset better now.
