### ISSUE TITLE
`safeHead`, etc. may not be necessary for Maybe

### ISSUE THREAD

**Issue by babakness** [MostlyAdequate/mostly-adequate-guide#454]
Hello, given that the `map` for `Maybe` Monad is given by

```javascript
  map(fn) {
    return this.isNothing ? this : Maybe.of(fn(this.$value));
  }
```

And that `safeHead` is defined as `compose(Maybe.of,head)`, it seem that one could simply do

```javascript
.map(head)
```

Instead of

```javascript
.chain(safeHead)
```

As both will result in `this.isNothing` to be `true` should the value returned by `head` return `null` or `undefined`

**Comment by KtorZ** [comment]
This is because `null` / `undefined` exists in JavaScript though in theory, you introduce `Maybe` / `Either` to cope with this and start thinking without them. So now, in that context, if you try to think of:

```
head :: [a] -> a
```

It becomes what is called a _partial_ function, which means, a function that can only operate on a partial subset of its input domain. The function isn't defined on the whole domain. In that case, we have a problem for empty list. In languages like Haskell or PureScript that don't have representation for null (ignoring Haskell's bottom here), then, the only resolution possible for that function when given an empty list is to throw at runtime. 
Thus, for empty list, `map(head)` doesn't actually make sense EVEN THOUGH, our JavaScript implementation would allow it. A better `head` for us would be something like:

```js
// head :: [a] -> a
function head(xs) {
     assert(!isEmpty(xs));
     return xs[0];
}
```

and `safeHead` 

```js
// safeHead :: [a] -> Maybe a
function safeHead(xs) {
    return isEmpty(xs) ? Nothing : Just(xs[0]);
}
```

**Comment by babakness** [comment]
Yes, I understand this, I was pointing out that the implementation here (and on many implementations of Maybe), mapping of `head` and getting `undefined` will result in a the Nothing value for the Maybe type.
