### ISSUE TITLE
Chapter8 confuse about side-effect

### ISSUE THREAD

**Issue by Belyenochi** [MostlyAdequate/mostly-adequate-guide#467]
I don't understand why if the wrapper function is removed, the output will be indeterminate,` key => localStorage [key]; `should output the value corresponding to the current environment localStorage key, plus the wrapper function means closure and delayed execution, but The final result still depends on the current environment's localStorage

```
// getFromStorage :: String -> (_ -> String)
const getFromStorage = key => () => localStorage[key];
```
Could someone help me;-)?

**Comment by KtorZ** [comment]
Well, you actually answered it yourself already ;) 

> the wrapper function means closure and delayed execution, but The final result still depends on the current environment's localStorage

What we care about with such function is that the function itself is pure and returns the same output given the same inputs. What the function returns is actually a handle to trigger the side-effects that indeed, depends on the current environment's localStorage. 

The initial function however `getFromStorage` will be pure and return an `IO String` which is something we can reason about, map over and chain, without actually executing it. What it enables is a powerful way to construct your program and manipulate what-would-be the result of those actions without actually running them and then, only run them in one well-located place.

This should help you as a developer to push the execution and manipulation of side-effects to the boundaries of your program because in the end, it is quite annoying to work in `IO` (or in any Monad) and we prefer work with simpler types and _truly pure functions_ only (_truly pure_ here to mean functions that don't return any IO-wrapped value). Having the `IO` around helps you visualize what parts of your code is actually running side-effects and what part isn't. One big pitfall is actually to "spread" the IO through your codebase and for instance, have functions working from `IO String -> IO Int` instead of lifting a truly pure `String -> Int` into IO.

**Comment by Belyenochi** [comment]
Thanks a lot,I believe that I understand more deeply.
