### ISSUE TITLE
Links to gitbooks broken

### ISSUE THREAD

**Issue by frazjp65** [MostlyAdequate/mostly-adequate-guide#586]
The links to gitbooks all go to https://www.gitbook.com/?utm_source=legacy&utm_medium=redirect&utm_campaign=close_legacy. 

This is probably because the transition to from the legacy site to their new site.

Did you run through the [Migrating your content](https://blog.gitbook.com/product/wrapping-up-the-transition-to-the-new-gitbook#migrating-your-content) process?

**Comment by cjgmj** [comment]
I'm trying to download the PDF file but the link is broken. Also, I'm trying do it myself but I'm getting many errors. Can you put a link to the PDF file?

Thank you in advance.

**Comment by prescottbreeden** [comment]
You can get the link directly from here: https://mostly-adequate.gitbooks.io/mostly-adequate-guide/content/

**Comment by jamesstoneco** [comment]
I am coming across these broken links as well, in the book listed and linked above in the readme as well as in the repo readme. I think the links should be removed if they are not working.

**Comment by achimcc** [comment]
Same for me! Can't download the pdf's, and `npm run generate-pdf` is ending with errors :(

**Comment by cjgmj** [comment]
Finally, I was be able to run `npm run generate-pdf` following the next steps (in Windows):
1. In `package.json` I changed the script `setup` for `./node_modules/.bin/gitbook install`.
2. In `book.json` I changed `exercises@git+https://github.com/MostlyAdequate/plugin-exercises.git` for `exercises`.
3. I had to uninstall gitbook-cli inside the project and install it globally.
4. Inside the global installition of gitbook-cli in `C:\Users\YOUR_USER\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules\npm\node_modules` you have to run `npm install graceful-fs@4.2.0 --save`
5. Install [Calibre](https://calibre-ebook.com/download_windows64)

Once you follow this steps you are ready to run `npm run generate-pdf` (I think I don't forget anything).

**Comment by KtorZ** [comment]
The PDF & EPUB are now built automatically via Github Actions with build artefacts uploaded as a result: https://github.com/MostlyAdequate/mostly-adequate-guide/actions/runs/802457659

Note that the script for doing locally still _kinda works_ but they require an old version of node.js; I've been able to run them using an old LTS (v10.22.1) which I pinned down using dotfiles for those using nvm. 

There's also a bug in Calibre 4.9.x (which is apparently the one shipping on recent versions of Aptitude), which is fixed in more recent version; so updating Calibre is necessary to work around that. 

If anything, I'll invite those who want to build locally to have a look at the github workflow now running on each push to master: https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/.github/workflows/build.yml

Or simply, enjoy the build artefacts :ok_hand:

**Comment by hukka** [comment]
The links are still broken, though

**Comment by KtorZ** [comment]
What link? 

https://mostly-adequate.gitbook.io/mostly-adequate-guide/ 

This one works fine.

**Comment by hukka** [comment]
On that gitbook page, the link to pdf still points to https://www.gitbook.com/download/pdf/book/mostly-adequate/mostly-adequate-guide (epub and mobi similarly too)

**Comment by KtorZ** [comment]
Ah! That is weird, this gitbook page should have been rebuilt with the latest push. Seems like something is off with gitbook and the synchronization with Github.
